"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {api,API_BASE,Fact,SessionState,Status} from "../lib/api";
import {DemoGuide,Header,HeroInteraction,languages} from "../components/KathaUI";
const SID="demo-01",examples={"hi-en":"Main VIT Vellore mein second year student hoon. Family income around 4 lakh hai.","te-en":"Nenu VIT Vellore lo second year student. Family income around 4 lakh.","bn-en":"Ami VIT Vellore-e second year student. Family income around 4 lakh."};
const title=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()),money=(v:unknown)=>typeof v==="number"?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v):String(v??"");
export default function Home(){
 const [data,setData]=useState<SessionState|null>(null),[language,setLanguage]=useState<keyof typeof languages>("hi-en"),[text,setText]=useState(examples["hi-en"]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[speechAvailable,setSpeechAvailable]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[transcript,setTranscript]=useState(""),[candidates,setCandidates]=useState<Fact[]>([]),[answer,setAnswer]=useState(""),[uploadResult,setUploadResult]=useState(""),[adaptDone,setAdaptDone]=useState(false),[demoOpen,setDemoOpen]=useState(false),[showType,setShowType]=useState(false),[guided,setGuided]=useState(false),[documentType,setDocumentType]=useState("income_certificate");
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const load=useCallback(async()=>{try{setData(await api.session(SID));setError("")}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{load();api.config().then(c=>setSpeechAvailable(c.speech_available)).catch(()=>setSpeechAvailable(false));return()=>{if(timer.current)clearInterval(timer.current)}},[load]);
 async function typed(){if(!text.trim())return;setBusy("Understanding your story…");try{const r=await api.text(SID,language,text);setTranscript(r.normalized_text);setCandidates(r.extracted_candidate_facts);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function startRecording(){if(recording||!speechAvailable)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),mime=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm",r=new MediaRecorder(stream,{mimeType:mime});chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);setRecording(false);setBusy("KATHA is understanding…");const form=new FormData();form.append("file",new Blob(chunks.current,{type:mime}),"recording.webm");form.append("session_id",SID);form.append("language",language);try{const x=await api.speech(form);setTranscript(x.transcript);setCandidates(x.candidate_facts);await load();if(x.audio_url)new Audio(API_BASE+x.audio_url).play().catch(()=>{})}catch(e){setError((e as Error).message)}finally{setBusy("")}};recorder.current=r;r.start();setSeconds(0);setRecording(true);timer.current=setInterval(()=>setSeconds(s=>{if(s>=27)r.stop();return s+1}),1000)}catch{setError("Microphone permission was denied or no microphone is available.")}}
 function stopRecording(){if(recorder.current?.state==="recording")recorder.current.stop()}
 async function upload(type:string,file?:File){setBusy("Reading evidence…");setUploadResult("");const form=new FormData();form.append("session_id",SID);form.append("document_type",type);if(file)form.append("file",file);else form.append("fixture_mode","true");try{const r=await api.upload(form);setUploadResult(r.status==="VERIFIED"?`${title(type)} added with document provenance.`:r.message);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function submitAnswer(){const q=data?.questions[0];if(!q||!answer.trim())return;setBusy("Saving your answer…");try{setData(await api.answer(SID,q.concept,answer));setAnswer("")}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function play(){setBusy("Preparing voice…");try{const blob=await api.tts(`KATHA understood your information. ${data?.next_question||"Your application is ready for review."}`,language);new Audio(URL.createObjectURL(blob)).play()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function reset(s:string){setBusy("Resetting demo…");try{setData(await api.reset(SID,s));setTranscript("");setCandidates([]);setAdaptDone(false)}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 const resolutions=useMemo(()=>Object.fromEntries((data?.resolutions||[]).map(r=>[r.requirement_id,r])),[data]),groups=useMemo(()=>{const g:Record<string,any[]>={VERIFIED:[],KNOWN:[],NEEDS_YOU:[],CONFLICTS:[]};for(const r of data?.application.requirements||[]){const s=resolutions[r.id]?.status as Status;(s==="VERIFIED"?g.VERIFIED:s==="CONFLICT"?g.CONFLICTS:s==="STATED"?g.KNOWN:g.NEEDS_YOU).push(r)}return g},[data,resolutions]),needs=data?.questions.length||0,total=data?.application.requirements.length||0;
 const guideStep=!transcript?1:!data?.evidence.some(e=>e.type==="income_certificate")?2:needs>0?3:4;
 return <main><Header language={language} onLanguage={l=>{setLanguage(l);setText(examples[l])}} demoOpen={demoOpen} onDemo={()=>setDemoOpen(!demoOpen)}/>
 <HeroInteraction speechAvailable={speechAvailable} recording={recording} seconds={seconds} busy={!!busy} onSpeak={recording?stopRecording:startRecording} onType={()=>{setShowType(true);requestAnimationFrame(()=>document.querySelector("#type")?.scrollIntoView({behavior:"smooth"}))}} onEvidence={()=>document.querySelector("#evidence")?.scrollIntoView({behavior:"smooth"})}/>
 {guided&&<DemoGuide step={guideStep} onClose={()=>setGuided(false)}/>} 
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}{busy&&<div className="busy" role="status">{busy}</div>}
 {showType&&<section className="type-panel reveal" id="type"><div><p className="kicker">Your words, your language</p><h2>Type your story</h2><p>Clearly marked example for {languages[language]}—edit it freely.</p></div><div className="type-control"><label className="sr-only" htmlFor="story">Tell KATHA your story</label><textarea id="story" value={text} onChange={e=>setText(e.target.value)} autoFocus/><button className="primary" onClick={typed} disabled={!!busy}>Tell KATHA</button></div></section>}
 {transcript&&<section className="understood"><div><p className="kicker">You said</p><p className="quote">“{transcript}”</p></div><div><p className="kicker">KATHA understood</p><div className="chips">{candidates.length?candidates.map(f=><span key={f.id}>{title(f.concept)} · {f.concept.includes("income")?money(f.value):String(f.value)}{f.precision==="approximate"?" ≈":""}</span>):<span>No new fact was safely inferred</span>}</div><button className="hear" onClick={play} disabled={!speechAvailable}>▶ Hear response</button></div></section>}
 {adaptDone&&<p className="correction-success" role="status">✓ Correction remembered. KATHA will use it as context next time.</p>}
 {data&&<><section className="compression"><p>KATHA reduced this application to what still needs your attention.</p><div className="compression-flow"><div><b>{total}</b><span>requirements</span></div><i>→</i><div><b>{data.preflight.resolved}</b><span>resolved</span></div><i>→</i><div className="accent"><b>{needs}</b><span>need you</span></div></div></section>
 <section className="journey"><div className="main-column"><p className="kicker">Application workspace</p><h2>{data.application.title}</h2>{Object.entries(groups).map(([name,items])=>items.length>0&&<details className={`group group-${name}`} open={name==="NEEDS_YOU"||name==="VERIFIED"} key={name}><summary><span>{name.replace("_"," ")}</span><b>{items.length}</b></summary><div>{items.map(r=>{const facts=data.facts.filter(f=>f.concept===r.concept),verified=facts.find(f=>f.status==="VERIFIED"||f.source_type==="document"),fact=verified||facts.at(-1),prior=verified&&facts.find(f=>f.source_type==="user"),ev=data.evidence.find(e=>e.id===fact?.source_id);return <article className="requirement" key={r.id}><div><h3>{r.label}</h3><p className="value">{fact?(r.concept.includes("income")?money(fact.normalized_value):String(fact.normalized_value??fact.value)):"Not provided"}</p>{ev&&<p className="source">Source: {title(ev.type)} · {new Date(ev.uploaded_at).toLocaleDateString()}</p>}{prior&&<p className="prior">Previously stated: {prior.precision==="approximate"?"approximately ":""}{r.concept.includes("income")?money(prior.value):String(prior.value)}</p>}</div><span className={`status ${resolutions[r.id]?.status}`}>{resolutions[r.id]?.status}</span></article>})}</div></details>)}</div>
 <aside><section className="question-card"><p className="kicker">Minimum next step</p><h2>KATHA knows {data.preflight.resolved} of {total} requirements.</h2><p>Only {needs} thing{needs===1?"":"s"} still need you.</p><hr/><h3>{data.next_question||"No more questions."}</h3>{data.questions[0]&&<div className="answer-row"><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={title(data.questions[0].concept)} onKeyDown={e=>e.key==="Enter"&&submitAnswer()}/><button onClick={submitAnswer}>Save</button></div>}<p className="reason">{data.questions[0]?.reason}</p></section>
 <section className={`preflight-card ${data.preflight.status==="READY"?"ready":""}`}><p className="kicker">Application readiness</p><h2>{data.preflight.status==="READY"?"✓ Ready for review":"● Not ready"}</h2><p>{data.preflight.status==="READY"?"Every required fact is resolved or supported. Review before submission.":`${data.preflight.blockers.length} blockers remaining`}</p>{data.preflight.blockers.length>0&&<details><summary>View blocker details</summary>{data.preflight.blockers.map(b=><div className="blocker" key={b.concept}><b>{title(b.concept)}</b><span>{b.message}</span></div>)}</details>}<button className="preflight-refresh" onClick={load}>Run Preflight</button></section>
 {transcript.toLowerCase().includes("vit valor")&&!adaptDone&&<section className="adapt"><p className="kicker">KATHA Adapt</p><p>I heard: <s>VIT Valor</s></p><h3>Did you mean VIT Vellore?</h3><button onClick={async()=>{await api.correction(SID,language,"VIT Valor","VIT Vellore","college_name");setAdaptDone(true)}}>Yes, remember this</button></section>}</aside></section>
 <section className="evidence-section" id="evidence"><p className="kicker">Evidence & provenance</p><h2>Human claim → Evidence → Requirement → Ready</h2><label className="document-label" htmlFor="document-type">Document type</label><select id="document-type" value={documentType} onChange={e=>setDocumentType(e.target.value)}><option value="income_certificate">Income certificate</option><option value="student_certificate">Student certificate</option><option value="domicile_certificate">Domicile certificate</option></select><label className="dropzone"><span>Drop a file here, or <b>choose document</b></span><small>Text PDF or text file. Image OCR is not available yet.</small><input type="file" accept=".pdf,.txt" onChange={e=>e.target.files?.[0]&&upload(documentType,e.target.files[0])}/></label><div className="evidence-list">{data.evidence.length?data.evidence.map(e=><article key={e.id}><span>Document</span><h3>{title(e.type)}</h3><p>{e.filename}</p><b>✓ {e.verification_state}</b></article>):<p>No evidence uploaded yet.</p>}</div><div className="upload-grid"><span>Demo fixtures:</span>{["income_certificate","student_certificate","domicile_certificate"].map(t=><button key={t} onClick={()=>upload(t)} disabled={!!busy}>+ {title(t)}</button>)}</div>{uploadResult&&<p className="success">✓ {uploadResult}</p>}</section>
 {demoOpen&&<section className="demo reveal"><button className="guided-button" onClick={async()=>{await reset("initial");setGuided(true);setDemoOpen(false)}}>Start guided demo</button><div className="demo-controls">{["initial","partial","conflict","ready"].map(s=><button onClick={()=>reset(s)} key={s}>{title(s)}</button>)}</div></section>}</>}
 <footer><b>KATHA</b><p>AI interprets. Deterministic systems decide. Nothing is submitted automatically.</p></footer></main>}
