export const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
export type Status="VERIFIED"|"STATED"|"UNCERTAIN"|"DERIVED"|"MISSING"|"CONFLICT";
export type Fact={id:string;concept:string;value:unknown;normalized_value:unknown;source_type:string;source_id:string|null;status:Status;precision:"exact"|"approximate";unit?:string|null;period?:string|null;confidence?:number|null;source_span?:string|null;derived_from_fact_ids?:string[];derivation?:string|null;created_at:string};
export type Evidence={id:string;type:string;filename:string;source:string;verification_state:string;uploaded_at:string};
export type Requirement={id:string;concept:string;label:string;required:boolean;proof_required:boolean};
export type Resolution={requirement_id:string;status:Status;explanation:string;evidence_ids:string[]};
export type Question={concept:string;question:string;reason:string;type:"requirement"|"clarification";known_value?:unknown;missing_qualifier?:string|null;fact_id?:string|null;options?:string[];localized_questions?:Record<string,string>};
export type SessionState={application_id:string;session_id:string;application:{id:string;program_id:string;title:string;requirements:Requirement[];readiness:string;resolved_count:number};facts:Fact[];evidence:Evidence[];resolutions:Resolution[];questions:Question[];next_question:string|null;preflight:{status:string;resolved:number;missing:number;uncertain:number;conflicts:number;blockers:{concept:string;message:string}[]};corrections:{heard_value:string;corrected_value:string;concept:string;verified:boolean}[]};
export class ApiError extends Error{constructor(message:string,public status=0,public code="request_failed"){super(message)}}
async function request<T>(path:string,init:RequestInit={},timeout=15000):Promise<T>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(API_BASE+path,{...init,signal:controller.signal});const data=await response.json().catch(()=>null);if(!response.ok){const detail=data?.detail;throw new ApiError(typeof detail==="string"?detail:detail?.message||"KATHA could not complete that request.",response.status,detail?.code)}return data as T}catch(error){if(error instanceof ApiError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new ApiError("The request timed out. Please try again.",0,"timeout");throw new ApiError("KATHA cannot reach the backend. Check that FastAPI is running.",0,"offline")}finally{clearTimeout(timer)}}
const json=(value:unknown)=>({headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});
export type PublicConfig={sarvamConfigured:boolean;speechEnabled:boolean;semanticExtractionEnabled:boolean;ttsEnabled:boolean;documentAIEnabled:boolean;speech_available:boolean;max_recording_seconds:number};
export type SemanticMeta={provider:string;semantic_success:boolean;candidate_fact_count:number;fallback_used:boolean;fallback_reason:string|null};
export type InteractionResult={application_id:string;normalized_text:string;semantic:SemanticMeta;applied_facts:Fact[];candidate_facts?:Fact[];extracted_candidate_facts:Fact[];response_text:string;application:SessionState};
export type QuestionAnswerSpeechResult=InteractionResult&{transcript:string;detected_language?:string|null;audio_url?:string|null;tts_error?:{code:string;message:string}|null};
export const api={config:()=>request<PublicConfig>("/api/config"),application:(id:string)=>request<SessionState>(`/api/applications/${encodeURIComponent(id)}`),createApplication:()=>request<SessionState>("/api/applications",{method:"POST"}),resetApplication:(id:string)=>request<SessionState>(`/api/applications/${encodeURIComponent(id)}/reset`,{method:"POST"}),session:(id:string)=>request<SessionState>(`/api/session/${encodeURIComponent(id)}`),reset:(id:string,scenario:string)=>request<SessionState>(`/api/demo/reset/${encodeURIComponent(id)}?scenario=${scenario}`,{method:"POST"}),text:(application_id:string,language_mode:string,text:string)=>request<InteractionResult>("/api/interactions/text",{method:"POST",...json({application_id,language_mode,text})}),clarifyIncomePeriod:(application_id:string,fact_id:string,period:"monthly"|"annual")=>request<SessionState>("/api/clarifications/income-period",{method:"POST",...json({application_id,fact_id,period})}),answerText:(application_id:string,question_concept:string,question_text:string,language_mode:string,text:string)=>request<InteractionResult>("/api/interactions/answer/text",{method:"POST",...json({application_id,question_concept,question_text,language_mode,text})}),answerSpeech:(form:FormData)=>request<QuestionAnswerSpeechResult>("/api/interactions/answer/speech",{method:"POST",body:form},45000),answer:(session_id:string,concept:string,value:string)=>request<SessionState>("/api/answers",{method:"POST",...json({session_id,concept,value})}),correction:(session_id:string,language:string,heard_value:string,corrected_value:string,concept:string)=>request<{application:SessionState}>("/api/corrections",{method:"POST",...json({session_id,language,heard_value,corrected_value,concept,verified:true})}),speech:(form:FormData)=>request<any>("/api/interactions/speech",{method:"POST",body:form},45000),upload:(form:FormData)=>request<any>("/api/documents/upload",{method:"POST",body:form},30000),tts:async(text:string,language:string,application_id?:string)=>{const r=await fetch(API_BASE+"/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,language,language_mode:language,application_id})});if(!r.ok){const d=await r.json().catch(()=>null);throw new ApiError(d?.detail?.message||"Speech playback is unavailable.",r.status,d?.detail?.code)}return r.blob()}};
