export const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
export type Status="VERIFIED"|"STATED"|"UNCERTAIN"|"MISSING"|"CONFLICT";
export type Fact={id:string;concept:string;value:unknown;normalized_value:unknown;source_type:string;source_id:string|null;status:Status;precision:"exact"|"approximate";created_at:string};
export type Evidence={id:string;type:string;filename:string;source:string;verification_state:string;uploaded_at:string};
export type Requirement={id:string;concept:string;label:string;required:boolean;proof_required:boolean};
export type Resolution={requirement_id:string;status:Status;explanation:string;evidence_ids:string[]};
export type SessionState={session_id:string;application:{title:string;requirements:Requirement[];readiness:string;resolved_count:number};facts:Fact[];evidence:Evidence[];resolutions:Resolution[];questions:{concept:string;question:string;reason:string}[];next_question:string|null;preflight:{status:string;resolved:number;missing:number;uncertain:number;conflicts:number;blockers:{concept:string;message:string}[]};corrections:{heard_value:string;corrected_value:string;concept:string;verified:boolean}[]};
export class ApiError extends Error{constructor(message:string,public status=0,public code="request_failed"){super(message)}}
async function request<T>(path:string,init:RequestInit={},timeout=15000):Promise<T>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(API_BASE+path,{...init,signal:controller.signal});const data=await response.json().catch(()=>null);if(!response.ok){const detail=data?.detail;throw new ApiError(typeof detail==="string"?detail:detail?.message||"KATHA could not complete that request.",response.status,detail?.code)}return data as T}catch(error){if(error instanceof ApiError)throw error;if(error instanceof DOMException&&error.name==="AbortError")throw new ApiError("The request timed out. Please try again.",0,"timeout");throw new ApiError("KATHA cannot reach the backend. Check that FastAPI is running.",0,"offline")}finally{clearTimeout(timer)}}
const json=(value:unknown)=>({headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});
export const api={config:()=>request<{speech_available:boolean;max_recording_seconds:number}>("/api/config"),session:(id:string)=>request<SessionState>(`/api/session/${encodeURIComponent(id)}`),reset:(id:string,scenario:string)=>request<SessionState>(`/api/demo/reset/${encodeURIComponent(id)}?scenario=${scenario}`,{method:"POST"}),text:(session_id:string,language:string,text:string)=>request<any>("/api/interactions/text",{method:"POST",...json({session_id,language,text})}),answer:(session_id:string,concept:string,value:string)=>request<SessionState>("/api/answers",{method:"POST",...json({session_id,concept,value})}),correction:(session_id:string,language:string,heard_value:string,corrected_value:string,concept:string)=>request<any>("/api/corrections",{method:"POST",...json({session_id,language,heard_value,corrected_value,concept,verified:true})}),speech:(form:FormData)=>request<any>("/api/interactions/speech",{method:"POST",body:form},45000),upload:(form:FormData)=>request<any>("/api/documents/upload",{method:"POST",body:form},30000),tts:async(text:string,language:string)=>{const r=await fetch(API_BASE+"/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,language})});if(!r.ok){const d=await r.json().catch(()=>null);throw new ApiError(d?.detail?.message||"Speech playback is unavailable.",r.status,d?.detail?.code)}return r.blob()}};
